spring:
  profiles: prod
    rabbitmq:
      host: rabbit.tacocloud.com
      port: 5673
      username: tacoweb
      password: l3tm31n
      template:
        exchange: tacocloud.orders
        routing-key: kitchens.central
        receive-timeout: 30000

